name: MAUI Unit Tests

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - dev
      - "**"
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workloads
        run: dotnet workload install maui-android

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build Grocery.App/Grocery.App.csproj -f net8.0-android --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test TestCore/TestCore.csproj -f net8.0 --configuration Release --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maui unit tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true